export const MODERATORS = [
    "valimp",
    "raphael0202",
    "alex-off",
    "charlesnepote",
    "gala-nafikova",
    "manoncorneille",
    "stephane",
    "teolemon",
    "segundo",
    "tacite",
    "october-food-facts",
    "odinh",
    "jusdekiwi",
  ]